
package org.tempuri;

import com.heavyclient.generated.response.ArrayOfAddress;
import com.heavyclient.generated.response.ItineraryResponse;
import jakarta.jws.WebMethod;
import jakarta.jws.WebParam;
import jakarta.jws.WebResult;
import jakarta.jws.WebService;
import jakarta.xml.bind.annotation.XmlSeeAlso;
import jakarta.xml.ws.RequestWrapper;
import jakarta.xml.ws.ResponseWrapper;


/**
 * This class was generated by the XML-WS Tools.
 * XML-WS Tools 4.0.1
 * Generated source version: 3.0
 * 
 */
@WebService(name = "IServerService", targetNamespace = "http://tempuri.org/")
@XmlSeeAlso({
    com.heavyclient.generated.ors.ObjectFactory.class,
    com.heavyclient.generated.response.ObjectFactory.class,
    com.microsoft.schemas._2003._10.serialization.ObjectFactory.class,
    com.microsoft.schemas._2003._10.serialization.arrays.ObjectFactory.class,
    org.datacontract.schemas._2004._07.server.ObjectFactory.class,
    ObjectFactory.class
})
public interface IServerService {


    /**
     * 
     */
    @WebMethod(operationName = "GetOptions", action = "http://tempuri.org/IServerService/GetOptions")
    @RequestWrapper(localName = "GetOptions", targetNamespace = "http://tempuri.org/", className = "org.tempuri.GetOptions")
    @ResponseWrapper(localName = "GetOptionsResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.GetOptionsResponse")
    public void getOptions();

    /**
     * 
     * @param destLat
     * @param destLng
     * @param originLat
     * @param originLng
     * @return
     *     returns com.heavyclient.generated.response.ItineraryResponse
     */
    @WebMethod(operationName = "Itinerary", action = "http://tempuri.org/IServerService/Itinerary")
    @WebResult(name = "ItineraryResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "Itinerary", targetNamespace = "http://tempuri.org/", className = "org.tempuri.Itinerary")
    @ResponseWrapper(localName = "ItineraryResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.ItineraryResponse")
    public ItineraryResponse itinerary(
        @WebParam(name = "OriginLat", targetNamespace = "http://tempuri.org/")
        Double originLat,
        @WebParam(name = "OriginLng", targetNamespace = "http://tempuri.org/")
        Double originLng,
        @WebParam(name = "DestLat", targetNamespace = "http://tempuri.org/")
        Double destLat,
        @WebParam(name = "DestLng", targetNamespace = "http://tempuri.org/")
        Double destLng);

    /**
     * 
     * @param text
     * @return
     *     returns com.heavyclient.generated.response.ArrayOfAddress
     */
    @WebMethod(operationName = "GetAddresses", action = "http://tempuri.org/IServerService/GetAddresses")
    @WebResult(name = "GetAddressesResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "GetAddresses", targetNamespace = "http://tempuri.org/", className = "org.tempuri.GetAddresses")
    @ResponseWrapper(localName = "GetAddressesResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.GetAddressesResponse")
    public ArrayOfAddress getAddresses(
        @WebParam(name = "text", targetNamespace = "http://tempuri.org/")
        String text);

}
