
package org.tempuri;

import jakarta.xml.ws.*;

import javax.xml.namespace.QName;
import java.net.MalformedURLException;
import java.net.URL;


/**
 * This class was generated by the XML-WS Tools.
 * XML-WS Tools 4.0.1
 * Generated source version: 3.0
 * 
 */
@WebServiceClient(name = "ServerService", targetNamespace = "http://tempuri.org/", wsdlLocation = "http://localhost:8733?wsdl")
public class ServerService
    extends Service
{

    private static final URL SERVERSERVICE_WSDL_LOCATION;
    private static final WebServiceException SERVERSERVICE_EXCEPTION;
    private static final QName SERVERSERVICE_QNAME = new QName("http://tempuri.org/", "ServerService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:8733?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        SERVERSERVICE_WSDL_LOCATION = url;
        SERVERSERVICE_EXCEPTION = e;
    }

    public ServerService() {
        super(__getWsdlLocation(), SERVERSERVICE_QNAME);
    }

    public ServerService(WebServiceFeature... features) {
        super(__getWsdlLocation(), SERVERSERVICE_QNAME, features);
    }

    public ServerService(URL wsdlLocation) {
        super(wsdlLocation, SERVERSERVICE_QNAME);
    }

    public ServerService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, SERVERSERVICE_QNAME, features);
    }

    public ServerService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public ServerService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns IServerService
     */
    @WebEndpoint(name = "BasicHttpBinding_IServerService")
    public IServerService getBasicHttpBindingIServerService() {
        return super.getPort(new QName("http://tempuri.org/", "BasicHttpBinding_IServerService"), IServerService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns IServerService
     */
    @WebEndpoint(name = "BasicHttpBinding_IServerService")
    public IServerService getBasicHttpBindingIServerService(WebServiceFeature... features) {
        return super.getPort(new QName("http://tempuri.org/", "BasicHttpBinding_IServerService"), IServerService.class, features);
    }

    private static URL __getWsdlLocation() {
        if (SERVERSERVICE_EXCEPTION!= null) {
            throw SERVERSERVICE_EXCEPTION;
        }
        return SERVERSERVICE_WSDL_LOCATION;
    }

}
